// Code generated by soul. DO NOT EDIT.
package settings

import (
	"net/http"

	logicHandler "github.com/solotoabillion/stab/internal/logic/admin/settings"
	"github.com/solotoabillion/stab/svc"
	"github.com/solotoabillion/stab/types"

	"github.com/labstack/echo/v4"
	"github.com/templwind/soul/webserver/httpx"
)

func DeleteSettingHandler(svcCtx *svc.ServiceContext, path string) echo.HandlerFunc {
	return func(c echo.Context) error {
		var req types.SettingRequest
		if err := httpx.Parse(c, &req, path); err != nil {
			c.Logger().Error(err)
			return c.JSON(http.StatusInternalServerError, map[string]interface{}{
				"error": "Internal Server Error",
				"msg":   err.Error(),
			})
		}
		l := logicHandler.NewDeleteSettingLogic(c.Request().Context(), svcCtx)
		resp, err := l.DeleteSetting(c, &req)
		if err != nil {
			c.Logger().Error(err)
			return c.JSON(http.StatusInternalServerError, map[string]interface{}{
				"error": "Internal Server Error",
				"msg":   err.Error(),
			})
		}
		return c.JSON(http.StatusOK, resp)
	}
}
