// Code generated by soul. DO NOT EDIT.
package settings

import (
	"net/http"

	logicHandler "github.com/solotoabillion/stab/internal/logic/admin/settings"
	"github.com/solotoabillion/stab/svc"

	"github.com/labstack/echo/v4"
)

func PostReloadSettingsHandler(svcCtx *svc.ServiceContext, path string) echo.HandlerFunc {
	return func(c echo.Context) error {
		l := logicHandler.NewReloadSettingsLogic(c.Request().Context(), svcCtx)
		resp, err := l.PostReloadSettings(c)
		if err != nil {
			c.Logger().Error(err)
			return c.JSON(http.StatusInternalServerError, map[string]interface{}{
				"error": "Internal Server Error",
				"msg":   err.Error(),
			})
		}
		return c.JSON(http.StatusOK, resp)
	}
}
