// Code generated by soul. DO NOT EDIT.
package handler

import (
	// Use new top-level paths
	admin "stab/internal/handler/admin"
	adminsettings "stab/internal/handler/admin/settings"
	api "stab/internal/handler/api"
	auth "stab/internal/handler/auth"
	billing "stab/internal/handler/billing"
	blog "stab/internal/handler/blog"
	developer "stab/internal/handler/developer"
	health "stab/internal/handler/health"
	knowledgebase "stab/internal/handler/knowledgebase"
	knowledgebaseadmin "stab/internal/handler/knowledgebase/admin"
	notifications "stab/internal/handler/notifications"
	profile "stab/internal/handler/profile"
	teams "stab/internal/handler/teams"
	// Removed imports for agentic_cs module handlers
	// support "stab/modules/agentic_cs/handler/support"
	// supportadmin "stab/modules/agentic_cs/handler/support/admin"
	// Import svc from its new top-level path
	"stab/svc"

	// Keep external imports
	// "github.com/golang-jwt/jwt/v5" // Removed: JWT logic handled elsewhere
	// "github.com/labstack/echo-jwt/v4" // Removed: JWT logic handled elsewhere
	"github.com/labstack/echo/v4"
)

// Removed: jwtCustomClaims struct - Not needed here

// RegisterHandlers registers only the core route handlers onto the provided Echo instance.
// Middleware (like JWT checks, admin checks) should be applied by the caller
// (either the consuming application or the main soul.RegisterRoutes function).
func RegisterHandlers(server *echo.Echo, svcCtx *svc.ServiceContext) {
	////////////////////////////////////////////////////////////
	// /api/knowledgebase routes
	////////////////////////////////////////////////////////////
	// Middleware removed from group definition
	knowledgebaseGroup := server.Group("/api/knowledgebase")
	knowledgebaseGroup.GET("/articles", knowledgebase.GetListArticlesHandler(svcCtx, "/articles"))
	knowledgebaseGroup.GET("/articles/search", knowledgebase.GetSearchArticlesHandler(svcCtx, "/articles/search"))
	knowledgebaseGroup.GET("/articles/:id", knowledgebase.GetArticleHandler(svcCtx, "/articles/:id"))

	////////////////////////////////////////////////////////////
	// /api/admin/knowledgebase routes
	////////////////////////////////////////////////////////////
	// Middleware removed from group definition
	knowledgebaseAdminGroup := server.Group("/api/admin/knowledgebase")
	knowledgebaseAdminGroup.POST("/articles", knowledgebaseadmin.PostCreateArticleHandler(svcCtx, "/articles"))
	knowledgebaseAdminGroup.PUT("/articles/:id", knowledgebaseadmin.PutUpdateArticleHandler(svcCtx, "/articles/:id"))
	knowledgebaseAdminGroup.DELETE("/articles/:id", knowledgebaseadmin.DeleteArticleHandler(svcCtx, "/articles/:id"))

	////////////////////////////////////////////////////////////
	// /health routes
	////////////////////////////////////////////////////////////
	// Middleware removed from group definition
	healthGroup := server.Group("/health")
	healthGroup.GET("/healthz", health.GetHealthCheckHandler(svcCtx, "/healthz"))
	healthGroup.GET("/readyz", health.GetReadinessCheckHandler(svcCtx, "/readyz"))
	healthGroup.GET("/livez", health.GetLivenessCheckHandler(svcCtx, "/livez"))

	////////////////////////////////////////////////////////////
	// /api routes
	////////////////////////////////////////////////////////////
	// Middleware removed from group definition
	apiGroup := server.Group("/api")
	apiGroup.GET("/plans", api.GetPlansHandler(svcCtx, "/plans"))

	////////////////////////////////////////////////////////////
	// /api/auth routes
	////////////////////////////////////////////////////////////
	// Middleware removed from group definition
	authGroup := server.Group("/api/auth")
	authGroup.POST("/register", auth.PostRegisterUserHandler(svcCtx, "/register"))
	authGroup.POST("/login", auth.PostLoginUserHandler(svcCtx, "/login"))
	authGroup.POST("/forgot-password", auth.PostForgotPasswordHandler(svcCtx, "/forgot-password"))
	authGroup.POST("/reset-password", auth.PostResetPasswordHandler(svcCtx, "/reset-password"))
	authGroup.POST("/login/code", auth.PostRequestLoginCodeHandler(svcCtx, "/login/code"))
	authGroup.POST("/login/verify", auth.PostVerifyLoginCodeHandler(svcCtx, "/login/verify"))
	authGroup.GET("/login/google", auth.GetGoogleLoginHandler(svcCtx, "/login/google"))
	authGroup.GET("/callback/google", auth.GetGoogleCallbackHandler(svcCtx, "/callback/google"))

	////////////////////////////////////////////////////////////
	// /api/blog routes
	////////////////////////////////////////////////////////////
	// Middleware removed from group definition
	blogGroup := server.Group("/api/blog")
	blogGroup.GET("/posts", blog.GetListPublishedPostsHandler(svcCtx, "/posts"))
	blogGroup.GET("/posts/:slug", blog.GetPostBySlugHandler(svcCtx, "/posts/:slug"))
	blogGroup.GET("/tags/:tagSlug/posts", blog.GetListPostsByTagHandler(svcCtx, "/tags/:tagSlug/posts"))
	blogGroup.GET("/categories/:categorySlug/posts", blog.GetListPostsByCategoryHandler(svcCtx, "/categories/:categorySlug/posts"))

	////////////////////////////////////////////////////////////
	// /api/profile routes
	////////////////////////////////////////////////////////////
	// Middleware removed from group definition
	profileGroup := server.Group("/api/profile")
	profileGroup.GET("", profile.GetProfileHandler(svcCtx, ""))
	profileGroup.POST("/regenerate-apikey", profile.PostRegenerateApiKeyHandler(svcCtx, "/regenerate-apikey"))
	profileGroup.POST("/revoke-apikey", profile.PostRevokeApiKeyHandler(svcCtx, "/revoke-apikey"))
	profileGroup.DELETE("/apikey", profile.DeleteApiKeyHandler(svcCtx, "/apikey"))
	profileGroup.POST("/change-email", profile.PostChangeEmailHandler(svcCtx, "/change-email"))
	profileGroup.GET("/preferences/email", profile.GetEmailPreferencesHandler(svcCtx, "/preferences/email"))
	profileGroup.PUT("/preferences/email", profile.PutUpdateEmailPreferencesHandler(svcCtx, "/preferences/email"))
	profileGroup.GET("/settings/security", profile.GetSecuritySettingsHandler(svcCtx, "/settings/security"))

	////////////////////////////////////////////////////////////
	// /api/billing routes
	////////////////////////////////////////////////////////////
	// Middleware removed from group definition
	billingGroup := server.Group("/api/billing")
	billingGroup.POST("/checkout-session", billing.PostCreateCheckoutSessionHandler(svcCtx, "/checkout-session"))
	billingGroup.POST("/portal-session", billing.PostCreatePortalSessionHandler(svcCtx, "/portal-session"))
	billingGroup.GET("/subscription", billing.GetSubscriptionHandler(svcCtx, "/subscription"))
	billingGroup.GET("/invoices", billing.GetInvoicesHandler(svcCtx, "/invoices"))
	billingGroup.POST("/add-ons/:addonId", billing.PostAddAddonHandler(svcCtx, "/add-ons/:addonId"))
	billingGroup.DELETE("/add-ons/:addonId", billing.DeleteRemoveAddonHandler(svcCtx, "/add-ons/:addonId"))
	billingGroup.POST("/webhook", billing.PostStripeWebhookHandler(svcCtx, "/webhook")) // Note: Webhook might need special handling outside normal auth

	////////////////////////////////////////////////////////////
	// /api/teams routes
	////////////////////////////////////////////////////////////
	// Middleware removed from group definition
	teamsGroup := server.Group("/api/teams")
	teamsGroup.POST("", teams.PostCreateTeamHandler(svcCtx, ""))
	teamsGroup.GET("", teams.GetListTeamsHandler(svcCtx, ""))
	teamsGroup.GET("/:teamId", teams.GetTeamDetailsHandler(svcCtx, "/:teamId"))
	teamsGroup.GET("/:teamId/members", teams.GetListMembersHandler(svcCtx, "/:teamId/members"))
	teamsGroup.DELETE("/:teamId/members/:memberId", teams.DeleteRemoveMemberHandler(svcCtx, "/:teamId/members/:memberId"))
	teamsGroup.PATCH("/:teamId/members/:memberId/role", teams.PatchUpdateMemberRoleHandler(svcCtx, "/:teamId/members/:memberId/role"))
	teamsGroup.POST("/:teamId/invitations", teams.PostInviteMemberHandler(svcCtx, "/:teamId/invitations"))
	teamsGroup.GET("/:teamId/invitations", teams.GetListInvitationsHandler(svcCtx, "/:teamId/invitations"))
	teamsGroup.DELETE("/:teamId/invitations/:invitationId", teams.DeleteCancelInvitationHandler(svcCtx, "/:teamId/invitations/:invitationId"))
	teamsGroup.GET("/invitations/:token", teams.GetInvitationDetailsHandler(svcCtx, "/invitations/:token"))
	teamsGroup.POST("/invitations/:token/accept", teams.PostAcceptInvitationHandler(svcCtx, "/invitations/:token/accept"))
	teamsGroup.POST("/invitations/:token/decline", teams.PostDeclineInvitationHandler(svcCtx, "/invitations/:token/decline"))

	////////////////////////////////////////////////////////////
	// /api/developer routes
	////////////////////////////////////////////////////////////
	// Middleware removed from group definition
	developerGroup := server.Group("/api/developer")
	developerGroup.GET("/usage", developer.GetAPIUsageStatsHandler(svcCtx, "/usage"))
	developerGroup.GET("/rate-limit", developer.GetRateLimitStatusHandler(svcCtx, "/rate-limit"))

	////////////////////////////////////////////////////////////
	// /api/notifications routes
	////////////////////////////////////////////////////////////
	// Middleware removed from group definition
	notificationsGroup := server.Group("/api/notifications")
	notificationsGroup.GET("", notifications.GetListNotificationsHandler(svcCtx, ""))
	notificationsGroup.POST("/read-all", notifications.PostMarkAllNotificationsReadHandler(svcCtx, "/read-all"))
	notificationsGroup.POST("/:notificationId/read", notifications.PostMarkNotificationReadHandler(svcCtx, "/:notificationId/read"))

	// Removed route groups for agentic_cs module (/api/support and /api/admin/support)

	////////////////////////////////////////////////////////////
	// /api/admin routes
	////////////////////////////////////////////////////////////
	// Middleware removed from group definition
	adminGroup := server.Group("/api/admin")
	adminGroup.GET("/users", admin.GetListUsersAdminHandler(svcCtx, "/users"))
	adminGroup.GET("/users/:userId", admin.GetUserDetailsAdminHandler(svcCtx, "/users/:userId"))
	adminGroup.GET("/users/:userId/communications", admin.GetListUserCommunicationsHandler(svcCtx, "/users/:userId/communications"))
	adminGroup.POST("/users/:userId/communications", admin.PostSendCommunicationHandler(svcCtx, "/users/:userId/communications"))
	adminGroup.GET("/dashboard/metrics", admin.GetDashboardMetricsHandler(svcCtx, "/dashboard/metrics"))

	////////////////////////////////////////////////////////////
	// /api/admin/settings routes
	////////////////////////////////////////////////////////////
	// Middleware removed from group definition
	adminSettingsGroup := server.Group("/api/admin/settings")
	adminSettingsGroup.POST("/reload", adminsettings.PostReloadSettingsHandler(svcCtx, "/reload"))
	adminSettingsGroup.GET("", adminsettings.GetListSettingsHandler(svcCtx, ""))
	adminSettingsGroup.GET("/:category/:key", adminsettings.GetSettingHandler(svcCtx, "/:category/:key"))
	adminSettingsGroup.PUT("/:category/:key", adminsettings.PutUpdateSettingHandler(svcCtx, "/:category/:key"))
	adminSettingsGroup.POST("", adminsettings.PostCreateSettingHandler(svcCtx, ""))
	adminSettingsGroup.POST("/save", adminsettings.PostSaveSettingsHandler(svcCtx, "/save"))
	adminSettingsGroup.DELETE("/:category/:key", adminsettings.DeleteSettingHandler(svcCtx, "/:category/:key"))

	// Removed: Catchall group for static website - Consumer responsibility
}
